server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:8080
              predicates:
                - Path=/prod/**, /cat/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: productCircuitBreaker
                    fallbackUri: forward:/fallback/products

            - id: order-service
              uri: http://localhost:8081
              predicates:
                - Path=/order/**

            - id: payment-service
              uri: http://localhost:8082
              predicates:
                - Path=/pay/**

management:
  endpoints:
    web:
      exposure:
        include: "*"